README.md

I will update the Jupyter notebook to also note the `data_format_fn` necessity and the fast listing component in a separate CL.

Update main README to note the examples in the demo directory

---

README.md

The update of the simple Colab demo follows in a different PR.

Update README to note the iterable dataset support

---

kokoro/build.sh
kokoro/continuous.cfg
kokoro/presubmit.cfg

add kokoro configs

---

kokoro/build.sh

Update build script to address pathing error.

update build script with correct path

---

kokoro/build.sh

Address build file complaints about directory command execution.

update config so git commands run in kokoro VM

---

kokoro/build.sh

Add submodule init to kokoro build.sh.

updated build.sh to include submodule init

---

kokoro/build.sh

Set all directories safe for kokoro VMs.

set all directoreis to safe

---

kokoro/build.sh

See https://docs.pytest.org/en/7.1.x/how-to/output.html#verbosity. This makes pytest more clearly report individual test cases in the logs.

Increase pytest verbosity in Kokoro

---

dataflux_pytorch/integration_tests/integration_test.py
dataflux_pytorch/tests/test_dataflux_checkpoint.py
kokoro/presubmit.cfg
kokoro/presubmit.sh

Update presubmit testing to include full map and iterable integration tests. Please check and approve any open internal CLs prior to reviewing this, as kokoro cannot run until those changes are committed.

Presubmit Integration Testing

---

dataflux_pytorch/dataflux_mapstyle_dataset.py
dataflux_pytorch/integration_tests/integration_test.py
dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
demo/simple_map_style_dataset.py

I'm not seeing it improve or decrease performance unfortunately, but it's worth adding so that we can test it on some different use cases.

Add threaded download to map-style dataset.

---

README.md

Briefly cover 429 errors with troubleshooting steps and actions.

update readme with 429 info

---

.vscode/extensions.json
.vscode/settings.json

This will make sure we're all using the same formatter and settings.

Standardize Python extensions and formatting settings.

---

dataflux_pytorch/benchmark/lightning_checkpoint_benchmark.py
dataflux_pytorch/dataflux_checkpoint.py
dataflux_pytorch/dataflux_iterable_dataset.py
dataflux_pytorch/dataflux_mapstyle_dataset.py
dataflux_pytorch/integration_tests/integration_test.py
dataflux_pytorch/lightning/__init__.py
dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
dataflux_pytorch/tests/test_dataflux_checkpoint.py
demo/image-segmentation/arguments.py
demo/image-segmentation/data_loader.py
demo/image-segmentation/model/layers.py
demo/image-segmentation/model/losses.py
demo/image-segmentation/model/unet3d.py
demo/image-segmentation/pytorch_loader.py
demo/image-segmentation/submit.py
demo/image-segmentation/train.py
demo/lightning/lightning_checkpoint.py
demo/simple_iterable_dataset.py
demo/simple_map_style_dataset.py

No changes to functionality, just formatting

Apply new formatter to all Python files.

---

README.md
dataflux_pytorch/dataflux_iterable_dataset.py
dataflux_pytorch/dataflux_mapstyle_dataset.py
dataflux_pytorch/tests/test_dataflux_iterable_dataset.py
dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py

Update interface to include configurable values passable from user.

Configure retry logic

---

demo/lightning/text-based/model.py

Add demo code for running text-based parquet model training with pytorch lightning and dataflux.

Lightning text

---

demo/lightning/image-segmentation/dataset.py

Addresses comments on PR #74 
Tested by running `train.py` locally

Fix DatafluxPytTrain.__getitem__

---

dataflux_pytorch/benchmark/README.md
dataflux_pytorch/benchmark/lightning_checkpoint_benchmark.py
dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
dataflux_pytorch/tests/test_dataflux_lightning_checkpoint.py
demo/lightning/Getting Started with Dataflux PyTorch Lightning Checkpoint with Google Cloud Storage.ipynb
demo/lightning/lightning_checkpoint.py

Internal Issue: b/352786281 
Parse bucket_name from ckpt_dir_path instead of setting it separately. Updated Unit tests, benchmarks code, demos and documentation.

Parse bucket name from ckpt directory name instead of separate parameter for bucket name

---

dataflux_pytorch/lightning/__init__.py
dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
dataflux_pytorch/lightning/gcs_filesystem.py
dataflux_pytorch/lightning/path_utils.py
dataflux_pytorch/tests/test_dataflux_lightning_checkpoint.py
dataflux_pytorch/tests/test_dataflux_lightning_gcs_filesystem.py

Add custom GCS writer. This will be used to demo multi node checkpointing. 
Sample train.py used to run the demo https://paste.googleplex.com/6277680464134144

Adding custom GCS Writer. 

---

demo/lightning/text-based/README.md

Update the parquet demo readme with benchmark results.

updated readme with benchmark results

---

demo/lightning/image-segmentation/requirements.txt
kokoro/bench.sh

Runs single node multi-process image segmentation workload as part of dataflux continuous integration tests

Run image training demo as part of continuous integ tests

---

demo/lightning/checkpoint/singlenode/continuous.py
demo/lightning/checkpoint/singlenode/train.py
kokoro/bench.sh

Add checkpointing single node demo as a continuous kokoro benchmark. Necessary internal changes have been made prior to this PR.

add benchmark code and update kokoro scripts

---

demo/lightning/image-segmentation/arguments.py
demo/lightning/image-segmentation/model.py

Make step time configurable

---

dataflux_pytorch/benchmark/README.md
dataflux_pytorch/benchmark/lightning_checkpoint_benchmark.py
dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
dataflux_pytorch/lightning/multipart.py
dataflux_pytorch/multipart_upload/__init__.py
dataflux_pytorch/multipart_upload/multipart.py
demo/lightning/checkpoint/singlenode/continuous.py
setup.py

Add base code for multipart upload. Followup CL will introduce comprehensive testing at which point we can enable it by default. Multiprocess code written by @andrewsg.

Multipart checkpoint upload

---

dataflux_pytorch/benchmark/README.md
dataflux_pytorch/benchmark/lightning_checkpoint_benchmark.py

Add code to clear kernel cache after saving checkpoints

---

dataflux_pytorch/benchmark/checkpointing/multinode/README.md

Updating the benchmarking Readme to correct the typo.

Correcting the typo in previous PR

---

dataflux_pytorch/benchmark/checkpointing/singlenode/README.md
dataflux_pytorch/benchmark/checkpointing/singlenode/train.py
dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
dataflux_pytorch/tests/test_dataflux_lightning_checkpoint.py
kokoro/bench.sh
kokoro/presubmit.sh

Set multipart upload as default behavior. Flag has been altered to allow for disabling feature if required.

set multipart upload to default behavior

---

dataflux_pytorch/benchmark/checkpointing/multinode/benchmark-deploy.yaml

Changing the hardcoded values to placeholder in benchmark-deploy.yaml

Changing hardcoded values to placeholders

---

demo/lightning/image-segmentation/README.md

Add info about the data loader's num_workers attribute

Update image segmentation benchmark README

---

README.md

Simplify and include checkpoint bench results in main README. Removed layers column to avoid confusion.

update main readme with checkpoing bench results

---

README.md
dataflux_pytorch/benchmark/checkpointing/singlenode/README.md
demo/lightning/checkpoint/singlenode/README.md

* Adds the number of model parameters and some information about the model used to the readmes
* Adds a note that the entire checkpoint file will be loaded in CPU memory

Update checkpoint readmes

---

dataflux_pytorch/benchmark/checkpointing/multinode/benchmark-deploy.yaml
dataflux_pytorch/benchmark/checkpointing/multinode/gcsfuse-pv.yaml
dataflux_pytorch/benchmark/checkpointing/multinode/gcsfuse-pvc.yaml
dataflux_pytorch/benchmark/checkpointing/multinode/train.py

Add support for benchmarking checkpoint save/restore to/from distributed filesystems

---

demo/lightning/checkpoint/simulated/multiprocessing_train.py

Add option to use FSSpec with simulated benchmarks.

Adding option to use FSspec with simulated benchmarks

---

kokoro/bench.sh

Fixes #<issue_number_goes_here>

update bench script to run simulated multinode bench

---

dataflux_pytorch/benchmark/llama-70b/README.md
dataflux_pytorch/benchmark/llama-70b/load.py

Fixes #<issue_number_goes_here>

add simple llama load benchmark and results

---

dataflux_pytorch/benchmark/checkpointing/multinode/README.md
dataflux_pytorch/benchmark/checkpointing/multinode/train_async_save.py
demo/lightning/checkpoint/multinode/strategies.py
demo/lightning/checkpoint/multinode/train.py
demo/lightning/checkpoint/simulated/multiprocessing_train.py

Add demo code for running PyTorch distributed async save checkpoints.
Also updates multinode checkpoint demo to specify the checkpoint save path.
Internal issue: [b/369834594](http://b/369834594)

PyTorch distributed checkpoint async save demo

---

dataflux_pytorch/benchmark/checkpointing/multinode/README.md

Update multi-node checkpoint benchmark instructions

---

dataflux_pytorch/benchmark/checkpointing/multinode/README.md

Update documentation to include multinode benchmark information.

update benchmark with multinode numbers

---

pyproject.toml

release 1.4.0

---

dataflux_pytorch/tests/test_multipart.py

Fixes broken tests introduced by upstream changes to multipart features.

fix multipart test
