GoogleCloudPlatform/gcs-connector-for-pytorch

README.md, dataflux_pytorch/dataflux_checkpoint.py
Add checkpointing support for the Dataflux Dataset.
From investigation it seems that we can confidently use [blob.open()](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_open) to create a file handler. 
* `blob.open("rb")` will return a `BlobReader`.
* `blob.open("wb", ignore_flush=True)` will return a `BlobWriter`.
Both types implement `io.BufferedIOBase` so can be passed into `torch.save()` and `torch.load()` like demonstrated in the README.
TODO: I haven't added unit tests to this yet -- I thought about writing mocks but decided to go with fakes. I wanted to share this PR first before making changes to `fake_gcs` so it would make more sense there. Will follow up on this next.
=> Add checkpointing support

dataflux_pytorch/tests/test_dataflux_checkpoint.py
Based on [added support of fake_gcs](https://github.com/GoogleCloudPlatform/dataflux-client-python/pull/15).
=> Add unit tests for checkpointing

pyproject.toml
Followed the following instructions to write a `pyproject.toml` to prepare for PyPI release:
1. [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
2. [Packaging Python Projects using setuptools ](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#package-discovery-and-namespace-packages)
Testing is not straightforward for this change because using the test PyPI index to upload the package will result in missing of all the packages such as `setuptools` and `torch`, which are only available in the real index.
Therefore, I went ahead to test in PROD by creating my own PROD account and upload the package [here](https://pypi.org/project/bernardhan-gcs-torch-dataflux/). You can view this and this will be looking identical to the …
=> Add pyproject.toml to prepare for PyPI release

README.md
The error was on an outdated README example where the `prefix` was an input to the dataset directly which is now in Config.
Tested by running through the README examples again.
=> fit typo on prefix

README.md, demo/image-segmentation/README.md, demo/simple-walkthrough/Getting Started with Dataflux Dataset for PyTorch with Google Cloud Storage.ipynb
I used a fresh `venv` to make sure that the new `pip install` command works. Therefore I'm updating the README and the two demos to note the update.
I tested by running a few cells in the Colab and verified that everything works as expected.
=> Update README and demos to note the new pip install command

dataflux_pytorch/dataflux_iterable_dataset.py, dataflux_pytorch/dataflux_mapstyle_dataset.py, dataflux_pytorch/tests/test_dataflux_iterable_dataset.py, dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
Implement DatafluxIterableDataset based on [design](https://docs.google.com/document/d/1SrodotAH7Z2QG6Lx-PZmCRRp4bC2u_U_58TmBjIDRz8/edit?resourcekey=0-4-2exqxutJbVrmSwD3LGyg&tab=t.0#heading=h.hakufr96ezb).
Based on https://pytorch.org/docs/2.1/data.html#torch.utils.data.IterableDataset, we will need to implement workload splitting in the `__iter__()` method.
Tested by running the unit test and running a simple main function:
```
if __name__ == "__main__":
ds = DataFluxIterableDataset(
project_name="dataflux-project",
bucket_name="bernardhan-test-real-demo",
config=Config(prefix="simple-demo-dataset"),
data_format_fn=lambda data: 11111111,
)
print(ds.objects)
data_loader = data.DataLoader(ds, batch_size=3, num_workers=3)
total = 0
for batch in data_loader:
print(len(batch))
print(batch) …
```
=> Add support for Dataflux Iterable Dataset

pyproject.toml
With the support of checkpointing and iterable dataset, I think we should be good to bump a MINOR_VERSION from 0 to 1.
I had released this package on PyPI because the demo installs the package directly from PyPI so it needs the iterable dataset changes. I have also created a 0.1.0 tag/release on Github.
=> Bump gcs-torch-dataflux from 0.0.0 to 0.1.0

dataflux_pytorch/dataflux_iterable_dataset.py
While working on the baseline performance numbers of Dataflux Iterable Dataset I found this critical bug that the previous implementation can ask each worker to download the whole dataset before applying `data_format_fn` to each item.
The bug is caused by using using the `[]` bracket to gather the results which break the generator pattern. Instead, we should use `()`. See more https://lerner.co.il/2018/06/08/python-parentheses-primer/.
The fix is tested by running the unit tests again and also rerun with the large dataset that exceeds the memory. Make sure that the memory utilization is correct. https://screenshot.googleplex.com/8g6A9qtHAiPGQ6r
As a retro:
1. The bug is introduced but didn't get caught by the unit test because in unit test we didn't test the logic of lazy generation of …
=> Fix Iterable Dataset bug on downloading the whole subset of data

README.md, demo/simple_iterable_dataset.py, demo/simple_map_style_dataset.py
Suggest to use "Display the rich diff" to review.
This PR updates the baseline performance numbers for Dataflux iterable dataset. Please review [this document](https://docs.google.com/document/d/19L2BKsXR9wTzMS0-hCvs6Wi4tTtutU2UfZoCV5OSuM4/edit?resourcekey=0-eMHwcwK4AddR2OUmo6iJIw&tab=t.0#heading=h.ar03bi1o136q) for the contexts.
This PR also updates the baseline performance numbers of the Dataflux map-style datasets to match the Tesseract results.
Finally, this PR adds the simple demo training loop that uses the iterable style dataset and updates the map style dataset.
TESTED by running `python3 -m demo.simple_map_style_dataset --project=dataflux-project --bucket=official-dataflux-tess --prefix=UNet3D/medium/3MB-150GB/train --epochs=5 --num-workers=96 --batch-size=256 …
=> Update baseline performance numbers for Dataflux datasets

kokoro/build.sh
This will make the logs more informative when debugging test failures on Kokoro.
This was used in
https://github.com/GoogleCloudPlatform/dataflux-client-python/pull/31 to help understand why JD's PR was failing tests on Kokoro despite passing locally.
=> Debug logging for Kokoro unit test build

pyproject.toml
Bump version to 1.0.0 to prepare for Cloud NEXT.
This PR also updates the dataflux-client-python submodule to point to the latest main at 2ab47cfaf0a52f87c619d552c526ab53dda7e8d9
Next step is to manually release to PyPI since we haven't set up the auto release yet.
=> bump version to 1.0.0

demo/image-segmentation/arguments.py, demo/image-segmentation/data_loader.py, demo/image-segmentation/run_and_time.sh
We currently set the number of data loader threads to the number of workers (GPUs). Having a separate flag for specifying number of data loader threads makes it easy to test with different values.
=> Add a new flag for specifying number of dataloader threads

README.md, dataflux_pytorch/dataflux_iterable_dataset.py, dataflux_pytorch/dataflux_mapstyle_dataset.py
Add explicit flag to disable compose. High scale operations must disable compose to avoid errors due to high read/write load caused by compose calls.
=> add disable_compose config

kokoro/build.sh, kokoro/presubmit.sh
Fixes the failing continuous tests.
We needed a `sudo apt-get -y update` to update the list of archives.
Tested by triggering a manual build [here](https://fusion2.corp.google.com/ci/kokoro/prod:cloud-storage-ml-infra-dataflux%2Fdataflux-pytorch%2Fcontinuous/activity/6172403c-3b0a-4954-9bce-6c58c64e98f9/log).
=> Fix continuous and presubmit tests

dataflux_pytorch/dataflux_checkpoint.py, dataflux_pytorch/dataflux_iterable_dataset.py, dataflux_pytorch/dataflux_mapstyle_dataset.py, dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py, dataflux_pytorch/tests/test_dataflux_checkpoint.py, dataflux_pytorch/tests/test_dataflux_iterable_dataset.py, dataflux_pytorch/tests/test_dataflux_lightning_checkpoint.py, dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
This ensures that we only have to update the version in one place when it changes, and the user agent gets set even for existing storage client objects.
=> Set Dataflux user-agent through dataflux_core.user_agent module

Dockerfile, README.md, demo/list-and-download/README.md, demo/list-and-download/iterable/deployment.yaml, demo/list-and-download/iterable/simple_iterable_dataset.py, demo/list-and-download/map/README.md, demo/list-and-download/map/deployment.yaml, demo/list-and-download/map/simple_map_style_dataset.py
A few things in this PR:
* Add retry flags to the demo loop code now that it's configurable
* Add a base-level Dockerfile to containerize the whole repo for testing on GKE
* Restructure the demos and give them GKE deployment files, along with a README
* Other minor fixes in the demo loops
=> Refactor Dataflux simple demo loops and add retry flags

dataflux_pytorch/dataflux_iterable_dataset.py, dataflux_pytorch/dataflux_mapstyle_dataset.py
These match the configs used in the demo/list-and-download benchmarks that I ran successfully. It ensures that retriable errors do not cause the entire job to fail while being retried, even if there's high load.
=> Update default retry config to match successful 1k-node benchmarks.

demo/lightning/text-based/model.py
Disable limit_train_batches by default and add configurable parameter.
=> add limit_train_batches param

demo/list-and-download/iterable/simple_iterable_dataset.py, demo/list-and-download/map/simple_map_style_dataset.py
This makes it easy to reproduce and test the issues in https://github.com/GoogleCloudPlatform/dataflux-pytorch/issues/58. 
I confirmed that the following fails right now:
- "spawn", with or without an initial client set
- "forkserver", with or without an initial client set
When I pulled in Akansha's PR https://github.com/GoogleCloudPlatform/dataflux-pytorch/pull/67, the above scenarios only fail when I set the initial client.
I also had to pull the `read_image_modified` definition out of inline since it couldn't be picked in that case.
=> Update demo loops to configure multiprocessing start method

dataflux_pytorch/dataflux_iterable_dataset.py, dataflux_pytorch/dataflux_mapstyle_dataset.py, dataflux_pytorch/tests/test_dataflux_iterable_dataset.py, dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
Fixes  https://github.com/GoogleCloudPlatform/dataflux-pytorch/issues/58
The pickling error was due to passing storage client to pytorch dataloader. When num_workers>0, pytorch uses multi-processing. Multi-processing fails as it cannot serialize/pickle storage client and lambda function.
=> For mac and windows skip passing client storage to avoid pickling error in multiprocessing

dataflux_pytorch/_helper.py, dataflux_pytorch/dataflux_iterable_dataset.py, dataflux_pytorch/dataflux_mapstyle_dataset.py, dataflux_pytorch/tests/test_dataflux_iterable_dataset.py, dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
Dataflux pytorch dataset fail when user does not have required permissions to create and delete composed objects.
If user doesn't have required permissions, set max_composite_size to 0.
Related Issue: https://github.com/GoogleCloudPlatform/dataflux-pytorch/issues/58#issuecomment-2231552178
=> Disable compose download when create and delete permissions are missing

kokoro/pypi.sh
Continuous test for dataflux PyPI package failed with `pyenv: pytest: command not found`
Reproduced the error and resolved by installing pytest. 
Sponge Link: http://sponge2.corp.google.com/e4828e42-9737-4243-aa62-f4a87c161ad9
=> Install pytest on running continuous  test for dataflux pypi package.

demo/lightning/image-segmentation/arguments.py, demo/lightning/image-segmentation/data.py, demo/lightning/image-segmentation/deploy.yaml
Default limit is too low (64MiB) causing OOMs for all cases where `num_workers > 0`. 
Tested by running successfully on 4 nodes with `prefetch_factor` set to `100` and `num_workers` set to `1`.
=> Configure shared memory size

dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
Remove the check to initialize bucket client only once, since we want to be able to pass different GCS buckets in save/restore/delete checkpointing functions.
This is in regards to comment on https://github.com/GoogleCloudPlatform/dataflux-pytorch/pull/85
=> Initialize new storage_client.bucket on every request

demo/lightning/image-segmentation/README.md, demo/lightning/image-segmentation/arguments.py, demo/lightning/image-segmentation/train.py
Training in skipped when `--listing_only` is passed to `train.py` and exits right after initializing the map style datasets.
=> Allow running demo code in listing-only mode

demo/lightning/image-segmentation/arguments.py, demo/lightning/image-segmentation/deploy.yaml, demo/lightning/image-segmentation/model.py
Update command in deployment file with batch_size and num_workers set to values that gave us best egress BW for 150MB dataset
Also, `Unet3DLightning.training_step` now returns a scalar (that represents loss) instead of None to skip actual training. This is because pytorch lightning does not allow skipping training when run on multiple nodes (returning None on single node training works just fine!)
=> Update defaults for batch_size and num_workers

dataflux_pytorch/benchmark/README.md, dataflux_pytorch/benchmark/lightning_checkpoint_benchmark.py, dataflux_pytorch/lightning/dataflux_lightning_checkpoint.py
This uses the Python Client Library's `blob.download_to_file` function to make checkpoint download quicker than passing the blob's reader to `torch.load` directly. 
* Benchmarked performance and added it to the README. The previous implementation performed similarly to the `Default`  (fsspec) numbers there
* Updated the benchmark to benchmark both checkpoint save and restore performance
=> Faster Lightning Checkpoint download

kokoro/bench.sh, kokoro/continuous_bench.cfg
Configs for kokoro continuous benchmarking. This will run single-node on a continuous schedule.
=> add continuous benchmark with kokoro

dataflux_pytorch/lightning/__init__.py, dataflux_pytorch/lightning/gcs_filesystem.py, dataflux_pytorch/tests/test_dataflux_lightning_gcs_filesystem.py
This adds custom GCS Reader to dataflux pytroch. 
Demo  POC is present in yashsha-tp branch (https://github.com/GoogleCloudPlatform/dataflux-pytorch/compare/yashsha-tp?expand=1) . I will add it to demo section after this PR is merged. 
create_stream is called with either "wb" (write binary) https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/filesystem.py#L318 
or "rb"(read binary) mode https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/filesystem.py#L643 & https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/filesystem.py#L679 
In read mode we need to pass Bytes instead of stream of bytes otherwise pickle.load fails.
=> Adding GCS Custom reader

dataflux_pytorch/dataflux_mapstyle_dataset.py, dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
To fix [#58](https://github.com/GoogleCloudPlatform/dataflux-pytorch/issues/58)
When multiprocess starts with spawn or forkserver,  passing storage client to fast-listing from dataflux pytorch will result in pickling error. Multi-processing fails as it cannot serialize/pickle storage client. 
- remove storage client creation for fast listing from dataflux_pytorch/dataflux_mapstyle_dataset.py.
The change got add in PR [#109]( https://github.com/GoogleCloudPlatform/dataflux-pytorch/pull/109)
=> Remove client initialization for fast listing from dataflux-pytorch

demo/lightning/checkpoint/singlenode/README.md
- Use auto number ordering to avoid typos in number sequence.
- Correctly indent sub list to allow auto sequence for entire list.
=> Minor formatting fixes in Lightning Checkpoint demo docs

dataflux_pytorch/benchmark/checkpointing/singlenode/README.md, dataflux_pytorch/benchmark/checkpointing/singlenode/train.py, kokoro/bench.sh
Got a failure in continuous benchmark test, seems like PR to add single node benchmarking to continuous runs was raised after I raised [PR#121 ](https://github.com/GoogleCloudPlatform/dataflux-pytorch/pull/121). 
Replaced all instances of `lightning_checkpoint_benchmark.py` with `checkpointing/singlenode/train.py`
=> Fixing build failures

kokoro/bench.sh
Continuous was unintentionally pointed at multinode, correcting so that it can pass.
=> fix benchmark pointed to incorrect file

dataflux_pytorch/benchmark/checkpointing/multinode/train.py
=> Print average times to save and load checkpoints together

dataflux_pytorch/benchmark/checkpointing/singlenode/README.md
Update README with findings from full benchmark pass with multipart, plus 10k passes with default, non-multipart, and multipart upload/download settings. Note that download does not include a multipart entry since the performance improvements only apply to upload as of today.
=> update lightning bench with multipart and 10k info

dataflux_pytorch/dataflux_checkpoint.py, dataflux_pytorch/tests/test_dataflux_checkpoint.py
This PR creates a simple wrapped bufferIO object that will write to GCS on flush. It should not introduce any differences in the existing method of implementation. I have tested it against the explicit example provided in our README.
=> update default dataflux to use multipart

dataflux_pytorch/dataflux_checkpoint.py
Update non-lightning dataflux to use blob.download_to_file for increased performance. This code has been tested against the README implementation for verification. This introduces no real change as the returned object is still a bytes buffer.
=> implement fast download for df checkpoint

dataflux_pytorch/benchmark/checkpointing/singlenode/README.md, dataflux_pytorch/benchmark/checkpointing/singlenode/train.py, kokoro/bench.sh
This also refactors the flag for no-dataflux since that option is mutually exclusive with the other checkpoint save options.
Internal issue: b/369839708
=> Add single node async benchmark execution to integration tests

dataflux_pytorch/benchmark/checkpointing/singlenode/train.py
Provide a mechanism for calling Checkpoint teardown when using manual checkpoint saves with AsyncCheckpointIO.
When using a large layer count, the `save_checkpoint()` task was not completing prior to calling `load_checkpoint()`, resulting in a race condition where `load_checkpoint()` would return a 404. This was caused by the removal of the teardown step, which issues a blocking shutdown call to the Threadpool executor, waiting for all tasks to complete before returning. We still want to override teardown so that it is not called during `trainer.fit()`, but we want to make sure the Threadpool tasks complete before making any calls to `load_checkpoint()`.
This PR introduces a new invocation point for the teardown method, which can be called after all `save_checkpoint()` 
calls and before …
=> Fix AsyncCheckpointIO race condition

dataflux_pytorch/dataflux_checkpoint.py, dataflux_pytorch/lightning/gcs_filesystem.py, dataflux_pytorch/tests/test_dataflux_checkpoint.py, dataflux_pytorch/tests/test_dataflux_lightning_gcs_filesystem.py
Updated GCSFileSystem to use multipart upload and faster download. Updated associated tests, ran locally and against real GPU cluster to validate.
=> add upload and download improvements to multinode

demo/lightning/image-segmentation/README.md
While running these benchmarks for fsspec, Matt observed that the per-step time was much higher than the documented time. I re-ran one of the benchmarks and confirmed that. For now, I'm updating the step time documented here. I will figure out what configured step time will lead to a per-step time of 1s, re-run the benchmarks and update the numbers.
=> Update documented step time

dataflux_pytorch/benchmark/checkpointing/simulated/multi_node_benchmark.py, demo/lightning/checkpoint/simulated/multiprocessing_train.py
This PR adds simulated benchmarking code for CPU, this version can be run directly on cloudtop as well as can be integrated into Kokoro runs (Hence it unblocks [b/361427435](https://b.corp.google.com/361427435) 
Also sharing code between demo & benchmarks so that there is no discrepancy between both the versions.  
<details>
<summary>Logs from sample run</summary>
```
(.venv) yashsha@yashsha1:~/vscode/dataflux-pytorch$ python3 -u demo/lightning/checkpoint/simulated/multiprocessing_train.py --project=gcs-tess, --ckpt-dir-path=gs://yashsha-us-east1-d/ --model-size=300 --world-size=5
/usr/local/google/home/yashsha/vscode/.venv/lib/python3.11/site-packages/torch/distributed/checkpoint/filesystem.py:490: UserWarning: Detected an existing checkpoint in …
```
=> Simulated CPU benchmarking code 

dataflux_pytorch/benchmark/checkpointing/multinode/README.md, dataflux_pytorch/benchmark/checkpointing/multinode/benchmark-deploy.yaml, dataflux_pytorch/benchmark/checkpointing/multinode/train.py, dataflux_pytorch/lightning/gcs_filesystem.py, demo/lightning/checkpoint/multinode/train.py
Several minor fixes/improvements for the multi-node checkpoint benchmark:
- Update the README with some missing instructions
- Run as a module rather than directly with Python so that imports work correctly
- Update `WORLD_SIZE` env var to `NUM_NODES` because PyTorch / PyTorch Lightning appear to use `WORLD_SIZE` for other purposes
- Set `use_orig_params=False` when creating the strategy, since this avoids the time-consuming step of flattening the optimizer state dict
- This happened on each node, so I'm hopeful that this gives us a better trend for throughput when scaling the number of nodes
- This also required updating the model's `configure_optimizers` to use `self.trainer.model.parameters` instead of `self.model.parameters` as in the default (see …
=> Multi-node checkpoint benchmark improvements

dataflux_pytorch/benchmark/checkpointing/multinode/README.md, dataflux_pytorch/benchmark/checkpointing/multinode/train.py, demo/lightning/checkpoint/multinode/train.py
Currently checkpoints are saved during `trainer.fit` which is not needed because we manually save checkpoints by calling `trainer.save_checkpoint`
=> Skip saving checkpoints during training

kokoro/bench.sh
Resolves ongoing continuous benchmark failures
=> Install checkpoint benchmark dependencies before running the benchmark

README.md
=> Correct table header row

dataflux_pytorch/dataflux_mapstyle_dataset.py, dataflux_pytorch/tests/test_dataflux_mapstyle_dataset.py
Move client creation from init to getitem and getitems. This way if a client is initialized in DataFluxMapStyleDataset, it will not be used in fast-list. Only user defined client to be used in fast-list.
=> Move client initialization to getitem and getitems

dataflux_pytorch/benchmark/checkpointing/multinode/train.py
Now it prints each save/load time individually and also all at the end. This makes it easier to understand how the data differs from sample to sample.
=> Update save/load print statements for FSDP benchmark

dataflux_pytorch/benchmark/checkpointing/multinode/train.py
This updates the benchmark to use the FSDP wrap policy defined in https://lightning.ai/docs/pytorch/stable/advanced/model_parallel/fsdp.html#identify-large-layers. 
Testing on a machine with 4 GPUs, before this change I get a CUDA OOM at a certain number of parameters for my model, and after the change I do not. 
I also removed the checkpoint restore path from the call to `trainer.fit` during load since this was making the trainer restore from that checkpoint an extra time, which is time consuming, and also explicitly deleting trainer/strategy/model prior to resetting them in case it helps prevent memory leaks.
=> Update auto wrap policy and remove duplicate load in trainer.fit

demo/lightning/checkpoint/multinode/train.py
This changes the structure of the model to match the Lightning FSDP demo, making it more realistic and therefore making it perform better.
Now on a machine with 4 x NVIDIA V100 (1B parameters / 32 layers, creates ~4GB checkpoint in total):
Dataflux:
##################################
Average time to save one checkpoint: 6.372414588928223 seconds
Average time to load one checkpoint: 20.229445457458496 seconds
##################################
Fsspec:
##################################
Average time to save one checkpoint: 18.570948839187622 seconds
Average time to load one checkpoint: 73.39956045150757 seconds
##################################
I also verified that FSDP is sharding the model appropriately, since I can run this when using 4 GPUs but hit CUDA OOM when running on 1 GPU
=> Refactor DemoTransformer model to match Lightning demo

dataflux_pytorch/benchmark/checkpointing/multinode/train.py, dataflux_pytorch/lightning/gcs_filesystem.py, demo/lightning/checkpoint/multinode/strategies.py, demo/lightning/checkpoint/multinode/train.py
This makes the constructor signature of our FSDP strategies more consistent with the base one, and ensures that the strategies can handle multiple different paths at runtime. `self.model` on the strategy is still set by the Lightning trainer when calling trainer.fit.
=> Remove model and path arguments from FSDP strategy constructors

README.md
Add feature references to primary README for multinode and async.
=> updated readme to include async and multinode features

README.md
* Clarify that we intend to provide initial triage of incoming requests within 24 business hours
* Add line for using the PyTorch trademarks from The Linux Foundation per their [brand guidance](https://pytorch.org/assets/brand-guidelines/PyTorch-Brand-Guidelines.pdf)
=> Add 24-hour triage and PyTorch naming lines to README

README.md
Google Cloud Storage "Connector for PyTorch" is now used consistently in place of previous "Accelerated Dataloader" and "Dataflux" names.
=> Update README.md with consistent naming

setup.py
Add demo.image_segmentation.model to setup.py as a quick fix for 'ModuleNotFoundError' in lightning image-segmentation benchmark. 
Verified that the fix works with rest of the continuous bench tests. 
Long term fix would be to remove demo/image-segmentation module and use python command with "-m".
=> Add demo.image_segmentation.model

README.md
Removed repeat documentation from main REAME. Documentation with slight repeats that require code examples have been left in to preserve clarity for users.
=> removed repeat information from main README

dataflux_pytorch/benchmark/requirements.txt, demo/lightning/checkpoint/requirements.txt
Fixes  https://github.com/GoogleCloudPlatform/gcs-connector-for-pytorch/security/dependabot/2
The vulnerability arises in torch  2.3.1 version. Changing it to the latest version.
=> Latest pytorch version
